# Generated by Django 6.0 on 2025-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional short description shown under the gallery title.', max_length=255),
        ),
    ]
