# Generated by Django 6.0 on 2025-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='page_type',
            field=models.CharField(choices=[('doc', 'Documentation'), ('policy', 'Policy')], max_length=10),
        ),
    ]
