# Generated by Django 6.0 on 2025-12-15 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberresource',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='memberresource',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberresource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='member_resources/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='memberresource',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
