# Generated by Django 5.2.7 on 2025-10-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('template_text', models.TextField(help_text='Use placeholders like [business_name], [business_type], [business_location], [target_audience]')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('seo', 'SEO'), ('social', 'Social Media'), ('blog', 'Blog & Content'), ('email', 'Email Marketing'), ('sales', 'Sales Pages'), ('local', 'Local Business'), ('ads', 'Advertising'), ('customer', 'Customer Engagement'), ('video', 'Video Scripts')], default='marketing', max_length=50)),
                ('tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
