# Generated by Django 5.2.7 on 2025-10-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='The actual prompt text')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('seo', 'SEO'), ('social', 'Social Media'), ('blog', 'Blog & Content'), ('email', 'Email Marketing'), ('sales', 'Sales Pages'), ('local', 'Local Business'), ('ads', 'Advertising'), ('customer', 'Customer Engagement'), ('video', 'Video Scripts')], default='marketing', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
