# Generated by Django 5.2.7 on 2025-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('ads', 'Advertising'), ('blog', 'Blog & Content'), ('customer', 'Customer Engagement'), ('email', 'Email Marketing'), ('general', 'General'), ('local', 'Local Business'), ('marketing', 'Marketing'), ('sales', 'Sales Pages'), ('seo', 'SEO'), ('social', 'Social Media'), ('video', 'Video Scripts')], default='marketing', max_length=50),
        ),
    ]
